/**
 * Who may call each route. Every route in the app MUST be listed here (a test checks this),
 * so nobody can add an open route by accident.
 *  - public:  anyone
 *  - user:    any signed in person
 *  - teacher: a signed in person with a teacher membership
 *  - student: a signed in person with a student membership
 */
export type Access = "public" | "user" | "teacher" | "student";

export const ROUTE_ACCESS: Record<string, Access> = {
  "GET /api/health": "public",
  "GET /api/openapi.json": "public",
  "GET /api/dev/outbox": "public", // answers "not found" unless running locally
  "GET /api/auth/options": "public",
  "GET /api/auth/google/start": "public",
  "GET /api/auth/google/callback": "public",
  "POST /api/auth/sign-up": "public",
  "POST /api/auth/verify-email": "public",
  "POST /api/auth/sign-in-link/request": "public",
  "POST /api/auth/sign-in-link/consume": "public",
  "POST /api/invites/accept": "public",
  "GET /api/me": "user",
  "POST /api/auth/sign-out": "user",
  "POST /api/auth/sign-out-everywhere": "user",
  "GET /api/auth/sessions": "user",
  "DELETE /api/auth/sessions/:id": "user",
  "GET /api/invites": "teacher",
  "POST /api/invites": "teacher",
  "POST /api/invites/:studentId/resend": "teacher",
  "DELETE /api/invites/:studentId": "teacher",
  "GET /api/courses": "teacher",
  "POST /api/courses": "teacher",
  "GET /api/courses/:id": "teacher",
  "PUT /api/courses/:id": "teacher",
  "POST /api/courses/:id/archive": "teacher",
  "POST /api/courses/:id/restore": "teacher",
  "GET /api/students": "teacher",
  "POST /api/students": "teacher",
  "POST /api/students/import": "teacher",
  "GET /api/students/:id": "teacher",
  "PUT /api/students/:id": "teacher",
  "POST /api/students/:id/archive": "teacher",
  "POST /api/students/:id/restore": "teacher",
  "GET /api/courses/:id/students": "teacher",
  "POST /api/courses/:id/students": "teacher",
  "PUT /api/courses/:id/students/:studentId": "teacher",
  "GET /api/students/:id/courses": "teacher",
  "GET /api/lessons": "teacher",
  "GET /api/courses/:id/lessons": "teacher",
  "POST /api/courses/:id/lessons": "teacher",
  "GET /api/lessons/:id": "teacher",
  "PUT /api/lessons/:id": "teacher",
  "POST /api/lessons/:id/cancel": "teacher",
  "POST /api/lessons/:id/restore": "teacher",
  "GET /api/lessons/:id/attendance": "teacher",
  "PUT /api/lessons/:id/attendance": "teacher",
  "GET /api/students/:id/attendance": "teacher",
  "GET /api/invoices": "teacher",
  "POST /api/invoices": "teacher",
  "POST /api/invoices/generate": "teacher",
  "GET /api/invoices/unbilled": "teacher",
  "GET /api/invoices/lessons": "teacher",
  "GET /api/invoices/:id": "teacher",
  "PUT /api/invoices/:id": "teacher",
  "DELETE /api/invoices/:id": "teacher",
  "PUT /api/invoices/:id/lessons": "teacher",
  "POST /api/invoices/:id/send": "teacher",
  "POST /api/invoices/:id/paid": "teacher",
  "POST /api/invoices/:id/unpaid": "teacher",
  "POST /api/invoices/:id/void": "teacher",
  "GET /api/payment-details": "teacher",
  "PUT /api/payment-details": "teacher",
  "GET /api/my/invoices": "student",
  "GET /api/my/invoices/:id": "student",
  "GET /api/courses/:id/assignments": "teacher",
  "POST /api/courses/:id/assignments": "teacher",
  "GET /api/assignments/:id": "teacher",
  "GET /api/grading/queue": "teacher",
  "GET /api/assignments/:id/submissions": "teacher",
  "GET /api/assignments/:id/submissions/:studentId": "teacher",
  "PUT /api/assignments/:id/submissions/:studentId/grade": "teacher",
  "POST /api/assignments/:id/submissions/:studentId/return": "teacher",
  "POST /api/assignments/:id/submissions/:studentId/request-revision": "teacher",
  "PUT /api/assignments/:id/extensions/:studentId": "teacher",
  "DELETE /api/assignments/:id/extensions/:studentId": "teacher",
  "GET /api/my/courses": "student",
  "GET /api/my/courses/:id": "student",
  "GET /api/my/work": "student",
  "GET /api/my/work/:id": "student",
  "PUT /api/my/work/:id/draft": "student",
  "POST /api/my/work/:id/submit": "student",
  "PUT /api/assignments/:id": "teacher",
  "POST /api/assignments/:id/publish": "teacher",
  "POST /api/assignments/:id/close": "teacher",
  "DELETE /api/assignments/:id": "teacher",
  "GET /api/courses/:id/materials": "teacher",
  "POST /api/courses/:id/materials": "teacher",
  "PUT /api/courses/:id/materials/:materialId": "teacher",
  "DELETE /api/courses/:id/materials/:materialId": "teacher",
};
