<script setup lang="ts">
import {
  Archive,
  ArrowLeft,
  Ban,
  BadgeCheck,
  Bell,
  BookOpen,
  CalendarDays,
  CalendarPlus,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  Clock,
  FileSpreadsheet,
  GraduationCap,
  House,
  Info,
  Link,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MonitorSmartphone,
  Pencil,
  Phone,
  Plus,
  Printer,
  Receipt,
  Repeat,
  RotateCcw,
  Search,
  Send,
  ShieldCheck,
  Smartphone,
  Sparkles,
  StickyNote,
  Trash2,
  TriangleAlert,
  Upload,
  UserPlus,
  Users,
  Video,
  X,
} from "lucide-vue-next";

// The one list of icons the app may use. Only these are put in the built files.
const icons = {
  archive: Archive,
  back: ArrowLeft,
  ban: Ban,
  verified: BadgeCheck,
  bell: Bell,
  book: BookOpen,
  calendar: CalendarDays,
  "calendar-plus": CalendarPlus,
  check: Check,
  left: ChevronLeft,
  right: ChevronRight,
  alert: CircleAlert,
  done: CircleCheck,
  attendance: ClipboardCheck,
  clock: Clock,
  sheet: FileSpreadsheet,
  cap: GraduationCap,
  home: House,
  info: Info,
  link: Link,
  "sign-out": LogOut,
  mail: Mail,
  place: MapPin,
  menu: Menu,
  devices: MonitorSmartphone,
  edit: Pencil,
  phone: Phone,
  plus: Plus,
  print: Printer,
  invoice: Receipt,
  repeat: Repeat,
  restore: RotateCcw,
  search: Search,
  send: Send,
  shield: ShieldCheck,
  mobile: Smartphone,
  spark: Sparkles,
  note: StickyNote,
  trash: Trash2,
  warning: TriangleAlert,
  upload: Upload,
  "user-plus": UserPlus,
  users: Users,
  video: Video,
  close: X,
} as const;

export type IconName = keyof typeof icons;

withDefaults(defineProps<{ name: IconName; size?: number }>(), { size: 20 });
</script>

<template>
  <component :is="icons[name]" :size="size" :stroke-width="1.75" aria-hidden="true" class="shrink-0" />
</template>
